spring.mail.password=kofn unwl uhfy gmwg
jwt.secret=a8F$kL92!xPq#7LmZ@1sD4vYtR8uWcXz9B7nM5Qe2R6T
spring.security.oauth2.client.registration.google.client-secret=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
spring.datasource.password=07100321