# ===============================
# SERVER
# ===============================
server.port=8080
frontend.url=http://localhost:5173
# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=clinic}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
# ===============================
# JACKSON (JSON format)
# ===============================
spring.jackson.serialization.indent_output=true

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# ===============================
# OAuth2
# ===============================
spring.security.oauth2.client.registration.google.client-id=587804048761-2jnuda34jqfa935dlnium60rim5ab942.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ===============================
# OTP
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amandullayevmuhammadali8@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# O'RNIGA
spring.profiles.active=local